inputs:
  name: 
    description: 'Your name'
    default: 'No name provided'
  upload-artifacts-path: 
    description: 'Path'
    default: "some/path"
runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.name }}.
      shell: bash
    - run: echo "Nice to meet you!"
      shell: bash
    - run: echo "$deploy_powershell_script"
      shell: bash
    - run: echo "$stop_powershell_script"
      shell: bash
    - run: echo "${{ inputs.upload-artifacts-path }}"
      shell: bash
    
