#https://stackoverflow.com/questions/65844033/conditional-needs-in-github-action

name: "Conditional dependency"

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: echo "build"

  deploy-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build, test]

    steps:
      - run: echo "deploy"
        
  deploy:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: build

    steps:
      - run: echo "deploy"
