env:
  default-branch: 'main'

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - ${{env.default-branch}}
  #     - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Get color
      run: echo "The selected branch is ${{env.default-branch}}"