# https://stackoverflow.com/questions/65227046/github-tag-action-does-not-add-tag

name: cron-test
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1 * * * *'
    - cron:  '*/2 * * * *'
  
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Is variable exported?
        run: |
          echo 'Hello'
