# https://stackoverflow.com/questions/65227046/github-tag-action-does-not-add-tag

name: build
on:
  pull_request:
    branches: ['*']
  push:
    branches: 
    - master
    - main
  
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          1.8,  # Minimum supported by Minecraft
          11,   # Current Java LTS
          15    # Latest version
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Get details
        run: echo "${{ github.event_name }} - ${{ runner.os }} - ${{ matrix.java }}"
      - name: Get details cond
        run: echo "${{ github.event_name }} - ${{ runner.os }} - ${{ matrix.java }}"
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
      - name: bump version and push tag
        id: tag_version
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
      - name: Create a GitHub release
        uses: actions/create-release@v1
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}