name: test-workflow

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Test1
        id: test1
        run: |
          i=0
          for f in $(ls $GITHUB_WORKSPACE/.github/workflows); do
            i=$((i+1))
            echo "file: $f"
            echo "::set-output name=f-$i::$f"
          done

          echo "::set-output name=counter::$i"

          h=""
          for g in $(ls $GITHUB_WORKSPACE/.github/workflows); do
            echo "file: $g"
            h="${h} $g"
          done

          echo "file: $h"

          echo "::set-output name=h::$g"

      - name: Test2
        run: |
          for file in "${{ steps.test1.outputs.f-1 }}"; do
            echo "$file.. detected"
          done

          echo "${{ steps.test1.outputs.h }}"
          for file in ${{ steps.test1.outputs.h }}; do
            echo "$file.. detected"
          done
