#https://stackoverflow.com/questions/67996484/how-to-create-a-folder-in-github-workflow
name: SO-023 Create folder

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create folder
        run: |
          mkdir myNewFolder && cp -R dist myNewFolder
          ls myNewFolder
          
