#https://stackoverflow.com/questions/67717380/github-workflow-does-not-trigger-on-push-for-path-based-filtering
name: SO-0222 Push to XYZ

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract commit
        run: |
          echo "Sending commit $GITHUB_SHA for $GITHUB_REPOSITORY"