name: artifact

on:
  workflow_dispatch:
  push:
    branches:
      - beta
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Archive build Artifact
      uses: actions/upload-artifact@master
      with:
        path: build        
