#https://stackoverflow.com/questions/65606498/how-to-access-github-tag-message-in-github-actions

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print tag
        run: |
          echo $TAG
          echo ${{ env.TAG }}
      - name: Print message
        run: |
          git tag -l --format='%(subject)' '${{ env.TAG }}'
      - name: Print message
        run: |
          git tag -l --format='%(subject)'
          git tag
      - name: Print message
        run: |
          git tag -l --format='%(contents)' '${{ env.TAG }}'