name: so-029-outputs

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
      output4: ${{ steps.step4.outputs.test-four }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - id: step4
        run: | 
          echo "::add-mask::bryko"
          echo "::set-output name=test-four::bryko"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - run: echo ${{ needs.job1.outputs.output3 }}
      - run: echo ${{ needs.job1.outputs.output4 }}

