name: APP Build
on:
  push:
    branches:
      - feature/test
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test-fail
        run: echo ${{ github.event.head_commit.message }}
  test-1:
    runs-on: ubuntu-latest
    if: ${{ contains( github.event.head_commit.message, 'test1') }}
    steps:
      - name: test-fail
        run: echo "test1"
  test-2:
    runs-on: ubuntu-latest
    if: ${{ contains( github.event.head_commit.message, 'test2') }}
    steps:
      - name: test-fail
        run: echo "test1"
  notify-slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [test-1, test-2]
    if: |
      always() &&
      (needs.test-1.result == 'success' || needs.test-1.result == 'skipped') &&
      (needs.test-2.result == 'success' || needs.test-2.result == 'skipped') && 
      (needs.test-1.result != 'skipped' && needs.test-2.result != 'skipped')
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: alert
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
