#https://stackoverflow.com/questions/65844033/conditional-needs-in-github-action

name: "Conditional dependency"

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: echo "build"

  deploy:
    runs-on: ubuntu-latest
    needs: contains(github.ref, "main") ? [build, test] : [build] #notice this line

    steps:
      - run: echo "deploy"
