name: dev-release

on:
  create:

    tags:

      - v*

jobs:

  build:

    name: setup environment

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node-version: [12.x]

    steps:

      - uses: actions/checkout@v2

        with:

          fetch-depth: 0

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

      - name: Create Release

        uses: ncipollo/release-action@v1

        with:

          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "test.ps1"
          bodyFile: "README.md"
          draft: true
