name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - run: echo 'stage ${{ inputs.target }}'